In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix


In [6]:
# Load dataset
iris = load_iris()
X, Y = iris.data, iris.target

In [7]:
# Train.test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


In [8]:
# Model
c1f = DecisionTreeClassifier()
c1f.fit(X_train, Y_train)

DecisionTreeClassifier()

In [9]:
# Predict
Y_pred = c1f.predict(X_test)

In [10]:
# Evalution
print("confusion_matrix:\n", confusion_matrix(Y_test, Y_pred))
print("\nclassification Report:\n", classification_report(Y_test, Y_pred, target_names=iris.target_names))


confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [13]:
from sklearn.linear_model import LinearRegression


In [14]:
model = LinearRegression()


In [20]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [21]:
iris = load_iris()
X = iris.data
y = iris.target

In [22]:
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)


In [23]:
# Model
model = GaussianNB()
model.fit(X_train, y_train)


GaussianNB()

In [24]:
# Predict
pred = model.predict(X_test)

In [25]:
# Accuracy
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.9333333333333333


In [28]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
pprint(df.head())

NameError: name 'pprint' is not defined

In [29]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [31]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [32]:
# Predict
y_pred = model.predict(X_test)

In [36]:
# Evalution
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 0.03711379440797686
R² Score: 0.9468960016420045


In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
for col in df.select_dtypes('object'):
  df[col] = LabelEncoder().fit_transfomer(df[col])

In [45]:
#Encode categorical variables
for col in df.select_dtypes('object'):
  if col!='Churn':
    df[col] = LabelEncoder().fit_transform(df[col])